## Librerias

In [9]:
import numpy as np

## Problema 1

Considere $D = \{d_1, \cdots d_n\}$ un conjunto de documentos y $T = \{t_1, \cdots t_m\}$ un conjunto de términos (palabras). Considere además, $TD = (TD_{i,j})_{i=1\cdots m, j = 1 \cdots n}$ como una matriz tal que $TD_{i, j}$ indica el número de veces que el término $t_i$ (palabra) aparece en el documento $d_j$ (Los documentos están el las columnas, las palabras en las filas). También, considere $l_i$ como la longitud (número de letras) del término $t_i$, y sea $L = (l_1, \cdots, l_m)$ un vector columna. Adicionalmente, asuma un proceso en el cual el documento $d_j$ is escogido aleatoriamente con probabilidad uniforme y el termino $t_i$, presente en el documento $d_j$,  es escogido con una probabilidad proporcional a la frecuencia de $t_i$ en el documento $d_j$.

Para las siguientes expresiones usted debe mostrar lo siguiente:

*   La expresión matemática de lo que se le pide en términos de $TD$, $L$, constantes (es decir en terminos de matrices, vectores, escalares) y operaciones algebraícas o del algebra lineal.
*   Una expresión en `numpy`, tal que al ser evaluada se obtenga, la matriz, el vector o el escalar requerido (La expresión debe estar descrita en términos del algebra lineal, es decir no se pueden usar estructuras de control, `for`, `while`, etc)
*   El resultado de las expresiones usando los siguientes datos:


$$
TD =  \begin{bmatrix}
2 & 3 & 0 & 3 & 7 \\  0 & 5 & 5 & 0 & 3 \\ 5 & 0 & 7 & 3 & 3 \\ 3 & 1 & 0 & 9 & 9 \\ 0 & 0 & 7 & 1 & 3 \\ 6 & 9 & 4 & 6 & 0 
\end{bmatrix}, \quad L = \begin{bmatrix}
5 \\  2 \\ 3 \\ 6 \\ 4 \\ 3 \\ 
\end{bmatrix}
$$





In [10]:
# Arrays for the computations

TD = np.array([[2, 3, 0, 3, 7],[0, 5, 5, 0, 3],[5, 0, 7, 3, 3],[3, 1, 0, 9, 9],[0, 0, 7, 1, 3],[6, 9, 4, 6, 0]])
L = np.array([[5, 2, 3, 6, 4, 3]]).T
m , n = TD.shape

TD, L

(array([[2, 3, 0, 3, 7],
        [0, 5, 5, 0, 3],
        [5, 0, 7, 3, 3],
        [3, 1, 0, 9, 9],
        [0, 0, 7, 1, 3],
        [6, 9, 4, 6, 0]]),
 array([[5],
        [2],
        [3],
        [6],
        [4],
        [3]]))

(a) Matriz $P(T, D)$ (cada posición de la matriz, $P(T, D)_{i,j}$ indica la probabilidad conjunta del término $t_i$ y el documento $d_j$, $P(t_j, d_j)$)

Escriba su expresión matemática a continuación, 

$$
P(T, D)_{i,j} = \frac{TD_{i,j}}{\sum_{i=1}^{m} \sum_{j=1}^{n} TD_{i,j}}
$$

In [13]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M1 = np.zeros((6, 5))
# su codigo aqui
Count_all_words_by_doc = TD.sum(axis=0)
Prob_choosing_doc = 1/5

M1 = TD/Count_all_words_by_doc*Prob_choosing_doc

# codigo para verificar su respuesta no modificar
print(M1.sum())
print(M1)

1.0
[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]


(b) Matriz $P(T|D)$

Escriba su expresión matemática a continuación, 

$$
P(T|D)_{i, j} = \frac{TD_{i, j}}{\sum_{k=1}^{m} TD_{k, j}}
$$

In [14]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M2 = np.zeros((6, 5))
# su codigo aqui
M2 = M1/Prob_choosing_doc

# codigo para verificar su respuesta no modificar
print(M2)
print(M2.sum(axis = 0))

[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]
[1. 1. 1. 1. 1.]


(c) Vector P(D)

Escriba su expresión matemática a continuación, 

$$
P(D)_j = \frac{1}{n}
$$

In [15]:
### Escriba e imprima el vector con los valores de ejemplo a continuación
P_D = np.zeros(5)
# su codigo aqui

P_D = M1.sum(axis=0)
# codigo para verificar su respuesta no modificar
print(P_D)

[0.2 0.2 0.2 0.2 0.2]


## Problema 2
Continuación problema anterior

(d) Vector P(T)

Escriba su expresión matemática a continuación, 

$$
P(T)_i = \frac{\sum_{j=1}^{n} TD_{i,j}}{\sum_{k=1}^{m} \sum_{j=1}^{n} TD_{k,j}}
$$

In [16]:
### Escriba e imprima el vector con los valores de ejemplo a continuación
P_T = np.zeros(5)
# su codigo aqui
P_T = M1.sum(axis=1)

# codigo para verificar su respuesta no modificar
print(P_T.sum())
print(P_T)

1.0
[0.14160606 0.12303382 0.17464229 0.20242929 0.09396047 0.26432806]


(e) Matriz $P(D|T)$

Escriba su expresión matemática a continuación, 

$$
P(D|T)_{i, j} = \frac{TD_{i, j}}{\sum_{k=1}^{n} TD_{i, k}}
$$

In [17]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M3 = np.zeros((6, 5))
# su codigo aqui

M3 = (M1*P_D).T/P_T
M3= M3.T

# codigo para verificar su respuesta no modificar
print(M3.sum(axis=1).reshape((m,1)))
print(M3)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
[[0.03530922 0.04707896 0.         0.03851915 0.07909266]
 [0.         0.09030941 0.07067693 0.         0.03901366]
 [0.07157487 0.         0.0697077  0.03123267 0.02748475]
 [0.03704997 0.01097777 0.         0.08083631 0.07113595]
 [0.         0.         0.12956419 0.0193505  0.05108531]
 [0.05674766 0.07566355 0.02631776 0.04127103 0.        ]]


(f) Escalar $E[l]$ (el valor esperado de la variable aleatoria $l$ que corresponde a la longitud de un término escogido aleatoriamente) (sin importar el documento)

Escriba su expresión matemática a continuación, 

$$
E[l] = \frac{1}{m} \sum_{i=1}^{m} l_i
$$

In [18]:
### Escriba e imprima el escalar con los valores de ejemplo a continuación
E_l = np.zeros(1)
# su codigo aqui

m = L.shape[0]
E_l = np.sum(L) / m

E_l

# codigo para verificar su respuesta no modificar
print(E_l)

3.8333333333333335
