## Librerias

In [4]:
import numpy as np

## Problema 2

Considere una cadena larga de resistencias como se muestra en la figura:

![](https://raw.githubusercontent.com/diegour1/CompMetodosComputacionales/main/DataFiles/image8.png)

Todos los resitores tienen las misma resistencia $R$. El voltage en la parte superior izquierda del sistema es $V_+ = 5 \text{V}$. El problema consiste en obtener los voltajes $V_1, \ldots, V_N$ de los puntos internos del circuito. 



a) Usando la ley de Ohm y la ley de corrientes de Kirchoff, la cual dice que la corriente total que fluye hacia afuera o hacia adentro de cada nodo del circuito es cero. Explique porqué los voltajes $V_1, \ldots, V_N$ cumplen con las siguientes ecuaciones.

$$3V_1 − V_2 − V_3 = V_+$$
$$− V_1 + 4V_2 − V_3 − V_4 = V_+,$$
$$\vdots$$
$$− V_{i − 2} − V_{i − 1} + 4V_i − V_{i + 1} − V_{i + 2} = 0,$$
$$\vdots$$
$$− V_{N − 3} − V_{N − 2}+ 4V_{N − 1} − V_N = 0,$$
$$− V_{N − 2} − V_{N − 1} + 3V_N = 0.$$

Pista: Para resolver esta pregunta se usa la ley de Ohm y la ley de corrientes de Kirchhoff. La cual dice que la corriente que fluye hacia adentro o hacia afuera de cada unión del circuito es cero. Por ejemplo para el voltaje $V_1$ se tiene que, 

$$
\frac{V_1-V_2}{R} + \frac{V_1-V_3}{R} + 
\frac{V_1-V_+}{R} = 0, 
$$

La fómrula general que se presentar arriba, resulta de la aplicación de la Ley de Ohm y Kirchoff. Por ley de Ohm, se tiene que $I = \frac{\Delta V}{R}$. Tomando las sumas para cada nodo se tendría que $\frac{V_N - V_{N-1}}{R} + \frac{V_N - V_{N-2}}{R} + \frac{V_N - V_{N+1}}{R} + \frac{V_N - V_{N+2}}{R} = 0 \leftrightarrow − V_{N − 2} − V_{N − 1} + 4V_N − V_{N + 1} − V_{N + 2} = 0$


b) Escriba las ecuaciones de la forma $A\vec{x} = \vec{b}$ encuentre los valores de la matriz $A$ y del vector $\vec{b}$, para $N=6$. Imprima estos dos resultados en el notebook.

$$
\begin{bmatrix}
    3 & -1 & -1 & 0 & 0 & 0 \\ -1&4&-1&-1&0&0 \\
    -1&-1&4&-1&-1&0 \\
    0&-1&-1&4&-1&-1 \\
    0&0&-1&-1&4&-1 \\
    0&0&0&-1&-1&3 \end{bmatrix}
    \begin{bmatrix}
     V_1 \\  V_2 \\ V_3 \\ V_4 \\ V_5 \\ V_6 \end{bmatrix}
     =
     \begin{bmatrix}
     5 \\  5 \\ 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}
$$

In [35]:
A = np.zeros((6, 6))
b = np.zeros(6)

# Tu codigo aqui

A = np.array([
    [3,-1,-1,0,0,0],
    [-1,4,-1,-1,0,0],
    [-1,-1,4,-1,-1,0],
    [0,-1,-1,4,-1,-1],
    [0,0,-1,-1,4,-1],
    [0,0,0,-1,-1,3]
])

b[0] = 5
b[1] = 5


# Codigo para la verificacion (no modificar)
print(A)
print(b)


[[ 3 -1 -1  0  0  0]
 [-1  4 -1 -1  0  0]
 [-1 -1  4 -1 -1  0]
 [ 0 -1 -1  4 -1 -1]
 [ 0  0 -1 -1  4 -1]
 [ 0  0  0 -1 -1  3]]
[5. 5. 0. 0. 0. 0.]


c) Escriba un programa que resuelva los valores de $V_i$ cuando $N=6$ es decir 6 nodos internos. Guarde e imprima los valores en el vector $\vec{x}$.



In [36]:
x = np.zeros(6)

x = np.linalg.solve(A,b)
# Codigo para la verificacion (no modificar)
print(x)

[3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


d) Encuentre la resistencia total $R_{(N=6)} = \alpha R$, para la red $N=6$, donde $\alpha$ es una constante, imprima el valor de $\alpha$.

In [39]:
alpha = 0

# Tu codigo aqui
I_total = (5-x[0]) + (5-x[1])
V = 5
alpha = 5/I_total
# Codigo para la verificacion (no modificar)
print(alpha)

1.7586206896551737


e) Explique qué haría usted para resolver la resistencia equivalente del circuito para un número infinito de nodos. 

Para hallar la resistencia equivalente para un circuito de un circuito infinito, se usarían las leyes de Ohm y las de Kirchoff para hallar los valores de lo voltajes y luego el de la resistencia total.