## Librerias

In [42]:
import numpy as np
import sympy as sym
from scipy import integrate as sci

## Problema 1

Considere la integral, 

$$ I = \int_0^1\sin^2(\sqrt{100x})\,dx$$

a) Cree la función `gauss_integrate(n)`, que reciba el grado `n` del polinomio de Gauss-Legendre y retorne la integral de la función pedida con el método de gauss-legendre. Puede usar la función `np.polynomial.legendre.leggauss` , para obtener los pesos y puntos de Legendre.

Puede usar el siguiente cuaderno como guia, [link](https://github.com/diegour1/CompMetodosComputacionales/blob/main/Notebooks/03%20-%20integracion_numerica.ipynb)

In [43]:
def function(x):
    return np.sin(np.sqrt(100*x))**2


def gauss_integrate(n):
  ## tu codigo aqui
    a,b = (0,1)
    gauss_int = 0
    puntos, weights = np.polynomial.legendre.leggauss(n)
    print(puntos)
    c1 = 0.5*(b-a)
    c2 = 0.5*(a+b)
    gauss_int = c1*np.sum(weights*function(c1*puntos + c2))
    return gauss_int




In [44]:
# Codigo para evaluar su resultado, no modificar
print(gauss_integrate(1))
print(gauss_integrate(2))
print(gauss_integrate(3))
print(gauss_integrate(4))
print(gauss_integrate(20))
print(gauss_integrate(100))

[0.]
0.5024843310662972
[-0.57735027  0.57735027]
0.6273262731105194
[-0.77459667  0.          0.77459667]
0.23603692720508807
[-0.86113631 -0.33998104  0.33998104  0.86113631]
0.42670930479562463
[-0.9931286  -0.96397193 -0.91223443 -0.83911697 -0.74633191 -0.63605368
 -0.510867   -0.37370609 -0.22778585 -0.07652652  0.07652652  0.22778585
  0.37370609  0.510867    0.63605368  0.74633191  0.83911697  0.91223443
  0.96397193  0.9931286 ]
0.4558325323090848
[-0.99971373 -0.99849195 -0.99629513 -0.99312494 -0.9889844  -0.98387754
 -0.97780936 -0.97078578 -0.96281365 -0.95390078 -0.94405587 -0.93328854
 -0.9216093  -0.90902957 -0.89556164 -0.88121868 -0.86601469 -0.84996453
 -0.83308388 -0.81538924 -0.79689789 -0.77762791 -0.75759812 -0.73682809
 -0.71533812 -0.6931492  -0.67028302 -0.64676191 -0.62260886 -0.59784747
 -0.57250193 -0.54659701 -0.52015802 -0.49321079 -0.46578165 -0.4378974
 -0.40958529 -0.38087298 -0.35178853 -0.32236034 -0.29261719 -0.26258812
 -0.23230248 -0.20178986 -0.1

b) Verifique sus resultados obtenidos usando la función `scipy.integrate.fixed_quad`. Imprima los resultados obtenidos con la libreria.


In [45]:
# tu codigo aqui
sci.fixed_quad(function,a=0,b=1,n=1)

(0.5024843310662972, None)

## Problema 2

En este problema vamos a reproducir los cálculos realizados en el siguiente [pdf](https://github.com/diegour1/CompMetodosComputacionales/blob/main/Lectures/01%20-%20Gauss%20Legendre%202.pdf) para dar una interpretación del método de Gauss Legendre para el caso $n = 4$. 





a) Con la libreria `sympy` cree la aproximación de taylor de grado 6 del polinomio $h(x)$, es decir cree la siguiente función e imprimala en la celda.


$$
h(x) = a + bx + c\frac{x^2}{2!} + d\frac{x^3}{3!} + e\frac{x^4}{4!} + f\frac{x^5}{5!} + g\frac{x^6}{6!}
$$


Pista: Use lo siguiente [link](https://stackoverflow.com/questions/37100053/how-to-define-a-mathematical-function-in-sympy
)


In [46]:
## tu codigo aqui
coeff = []
x = sym.Symbol('x')
h = 0
for i in range(7):
    coeff.append(sym.Symbol('a_'+str(i)))
for exponent in range(len(coeff)):
    h += coeff[exponent]*x**exponent/np.math.factorial(exponent)
h

a_0 + a_1*x + a_2*x**2/2 + a_3*x**3/6 + a_4*x**4/24 + a_5*x**5/120 + a_6*x**6/720

**b) Usando `sympy` cálcule:**

$$
\int_{-1}^1h(x) \ dx
$$

imprima el resultado de la integral.

Pista: debe resultar una función de $x$ con coeficientes, $a$, $c$, $e$, $g$.

In [47]:
# tu codigo aqui
sym.integrate(h,(x,-1,1))

2*a_0 + a_2/3 + a_4/60 + a_6/2520

**c) Encuentre los puntos en $x$ y los pesos $w$ de la cuadratura de Gauss de grado 4. Imprima los puntos y los pesos.**

In [48]:
## find the Cuadrature weights
# tu codigo aqui
X,W = np.polynomial.legendre.leggauss(4)
X,W

(array([-0.86113631, -0.33998104,  0.33998104,  0.86113631]),
 array([0.34785485, 0.65214515, 0.65214515, 0.34785485]))

**d) Usando la función $h(x)$ del punto a), evalúe el resultado de la cuadratura de Gauss de grado 4, es decir cálcule:**

$$
\sum_{i=1}^4w_ih(x_i)
$$

Imprima el resultado de la integral.

In [49]:
# tu codigo aqui
Sum = 0
for i in range(4):
    Sum += W[i]*h.evalf(subs={x: X[i]})
Sum

2.0*a_0 + 5.55111512312578e-17*a_1 + 0.333333333333333*a_2 + 0.0166666666666667*a_4 + 0.000396825396825397*a_6

**e) ¿Cuadran las funciones resultantes del punto b) y d)? Sí, no y por qué.**

Sí, las funciones cuadran (el término de $a_1$ es prácticamente cero y despreciable), esto es debido a que la interpretación geométrica de la cuadratura de Gauss, es la suma de los rectangulos bajo la curva con área $w_if(x_i)$ para $i \in I$ (siendo $I$ un conjunto de índices).

**f) ¿Qué interpretación geometrica daría a la cuadratura de Gauss?**

La interpretación geométrica de la cuadraturea de Gauss es una suma de rectángulos evaluados en ciertos puntos de la función de base dada por los pesos $w_i$.

**g) A partir de la integral de la función obtenida, cálcule:**

$$
\int_{-1}^1h(x)\ dx
$$

para la función 

$$
h(x) = 0.70458458 + 0.23544087x + 0.58528482x^2 + 0.1669135x^3 + 0.20669362x^4 + 0.4717781x^5 + 0.48755507x^6
$$

In [50]:
coeffs = np.array([0.70458458, 0.23544087, 0.58528482, 0.1669135 , 0.20669362, 0.4717781 , 0.48755507])    
   
def six_deg_function(x):
  return 0.70458458 + 0.23544087*x + 0.58528482*x**2 + 0.1669135*x**3 + 0.20669362*x**4 + 0.4717781*x**5 + 0.48755507*x**6


## tu codigo aqui

def gauss_integrate(n):
  ## tu codigo aqui
    a,b = (-1,1)
    gauss_int = 0
    puntos, weights = np.polynomial.legendre.leggauss(n)
    c1 = 0.5*(b-a)
    c2 = 0.5*(a+b)
    gauss_int = c1*np.sum(weights*six_deg_function(c1*puntos + c2))
    return gauss_int

gauss_integrate(n=4)


2.0213379365714284

**h) Evalúe la integral de $h(x)$ usando la función `integrate.fixed_quad`**

In [51]:
## tu codigo aqui
sci.fixed_quad(six_deg_function,a=-1,b=1,n=4)



(2.0213379365714284, None)

**i) ¿Qué cambiaría en este método si se integrara un polinomio de grado mayor a 6 con el método expuesto?**
Si el grado del polinomio fuera mayor a 7, la integral no sería exacta. Esto debido a que estamos trabajando con los pesos y valores del polinomio de Laguerre de grado 4 y la cuadratura es exacta para los polimonios con grado menor o igual a $2n -1$, siendo $n = 4$. Por lo que integral de un polimonio de grado 8 ya no debería ser exacta.