In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Álgebra lineal

**3.** Implemente un algoritmo que realice la multiplicación de dos matrices. Use el algoritmo para calcular:
$$AB = \begin{bmatrix} 1 & 0& 0 \\ 5 &1 &0 \\ -2 &3 &1  \end{bmatrix}\begin{bmatrix} 4 & -2& 1 \\ 0 &3 &7 \\ 0 &0 &2  \end{bmatrix}$$

In [11]:
AB = np.zeros((3,3))
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])

for i in range(len(A)):
    for j in range(len(B[:,0])):
        AB[i][j] = np.dot(A[i],B[:,j])
        
print(AB)
        

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


**4.** Muestre con detalle que la sustitución hacia adelante se expresa como: $$ x_i = b_i - \sum_{j=0}^{i-1}A_{ij}x_j$$

**Solución:** Teniendo en cuenta el sistema $$A\vec{x} = \vec{b}$$ se puede hacer la sustitución $L(U\vec{x}) = \vec{b}$ y la sustitución hacia adelante $L\vec{y} = \vec{b}$. Dado que la matriz $L$ tiene forma triangular inferior, se tiene que 
$$
\begin{bmatrix} 1 & 0 & \dots & 0 \\ \ell_{21} & 1 & \dots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ \ell_{n1} & \ell_{n2} & \dots & 1 \end{bmatrix}
\begin{bmatrix}
y_1 \\ y_2 \\ \vdots \\ y_n
\end{bmatrix} =
\begin{bmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{bmatrix}
$$
Es decir,
$$
\begin{align*}
y_1 &= b_1 \\
\ell_{21}y_1 + y_{2} &= b_2 \\
\ell_{31}y_1 + \ell_{32}y_{2} + y_3 &= b_3\\
\vdots \\
\sum_{j = 1}^{i-1}\ell_{ij}y_{j} + y_i &= b_i 
\end{align*}
$$
Esto es, entonces
$$y_i = b_i - \sum_{j=1}^{i-1}\ell_{ij}y_j$$
Como se quería. $\blacksquare$

**5.** Muestre con detaller que la sustitución hacia atrás se expresa como:

$$x_i = \frac{b_i - \displaystyle\sum_{j = i+1}^{n}A_{ij}x_j}{A_{ii}}$$

**Solución:** Teniendo en cuenta la sustitución $U\vec{x} = \vec{y}$. Dado que la matriz $U$ tiene forma triangular superior, se tiene que 
$$
\begin{bmatrix} u_{11} & u_{12} & \dots & u_{1n} \\ 0 & u_{22} & \dots & u_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \dots &u_{nn}\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}
= \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix}
$$
Lo cual se puede expresar como un conjunto de ecuacioens lineales
$$
\begin{align*}
u_{11}x_1 + u_{12}x_2 + u_{13}x_3 + u_{14}x_4 + \dots + u_{1n}x_n &= y_1 \\
u_{22}x_2 + u_{23}x_3 + u_{24}x_4 + \dots + u_{2n}x_n &= y_2 \\
 u_{33}x_3 + u_{34}x_4 + \dots + u_{3n}x_n &= y_3\\
 \vdots \\
 u_{ii}x_i + \sum_{j = i +1}^{n}u_{ij}x_j &= y_i
\end{align*}
$$
Despejando $x_i$, se tiene que 
$$x_i = \frac{y_i - \displaystyle\sum_{j=i+1}^{n}u_{ij}x_j}{u_{ii}}.$$

Como se quería. $\blacksquare$

**6.** Use el método de sobrerelajación sucesiva para solucionar el sistema:
$$
\left\{
\begin{align*}
3x_1 - x_2- x_3 = 1 \\
-x_1 + 3x_2 + x_3 = 3\\
2x_1 + x_2 +4x_3 = 7
\end{align*}
\right.
$$

In [22]:
def sor_solver(A, b, omega, initial_guess, convergence_criteria):

    phi = initial_guess[:]
    residual = np.linalg.norm(A @ phi - b)  # Initial residual
    while residual > convergence_criteria:
        for i in range(A.shape[0]):
            sigma = 0
            for j in range(A.shape[1]):
                if j != i:
                    sigma += A[i, j] * phi[j]
            phi[i] = (1 - omega) * phi[i] + (omega / A[i, i]) * (b[i] - sigma)
        residual = np.linalg.norm(A @ phi - b)
    return phi

residual_convergence = 1e-8
omega = 1.3

A = np.array([[3,-1,-1],
              [-1,3,1],
              [2,1,4]])

b = np.array([1, 3, 7])

initial_guess = np.zeros(3)

phi = sor_solver(A, b, omega, initial_guess, residual_convergence)
print("x_1: %s, x_2: %s, x_3: %s"%(phi[0],phi[1],phi[2]))

x_1: 1.0000000017524404, x_2: 0.9999999997215512, x_3: 0.9999999983063279


**7.** Implemente la descomposición LU para factorizar la siguiente matriz $A = LU$.
$$A = \begin{bmatrix} 4 & -2 & 1 \\ 20 & -7 & 12 \\ -8 & 13 & 17 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 \\ 5 & 1 & 0 \\ -2 & 3 & 1 \end{bmatrix} \begin{bmatrix} 4 & -2 & 1 \\ 0 & 3 & 7 \\ 0 & 0 & -2 \end{bmatrix}$$

In [71]:
def LU_fact(A):
    n = A[0].size
    L = np.identity(n)
    for i in range(0,n):
        for j in range(i+1,A[0].size):
            I = np.identity(n)
            I[j][i] = -A[j][i]/A[i][i]
            L[j][i] = A[j][i]/A[i][i]
            A = I@A
    return L,A

A = np.array([[4,-2,1],[20,-7,12],[-8,13,17]])

print("Lower matrix: \n %s \n Upper matrix: \n %s  "%LU_fact(A))

Lower matrix: 
 [[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]] 
 Upper matrix: 
 [[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]  


 **9.** Método de Jacobi: diagonalización de matrices simétricas.
 
 **(a)** Implemente el método de Jacobi para encontrar los valores y vectores propios de:
 $$A = \begin{bmatrix} 4 & 1 & 1 \\ 1 & 3 & 2 \\ 1 & 2 & 5 \end{bmatrix}$$